### ISSUE TITLE
Let's Encrypt with nip.io not working

### ISSUE THREAD

**Issue by mkjpryor-stfc** [cedadev/jasmin-appliances#76]
It always hits the rate limit. So does xip.io. Need to consider other options, including self-signed certificates.

**Comment by brtkwr** [comment]
Could always configure your own wildcard DNS to point to the ingress node... e.g. *.jasmin.io all redirect to the ingress node IP address?

Good to discover the rate limit though... {xip,nip}.io are fine for development but maybe not so great for prod usage.

**Comment by mkjpryor-stfc** [comment]
@brtknr You couldn't set up a single wildcard DNS - it would need to have similar features to xip.io/nip.io for resolving IPs, or you could only use it for one cluster.

There are self-service options for this which we could look at, e.g. https://github.com/elastic/hipio. Then we could have something like `<subdomain>.<ip>.caas.jasmin.ac.uk`, and we would create an `NS` record for `caas.jasmin.ac.uk` to point to the nameserver.

However, for now, `sslip.io` doesn't look so highly trafficked and is working :D
